import { GoodsType } from "../goods";

const goodsList: Partial<GoodsType>[] = [
  {
    name: 'Notebook Gamer Acer Nitro 5',
    description: 'O Acer Nitro 5 é um notebook gamer poderoso, ideal para jogos pesados e multitarefas.',
    brand: 'Acer',
    model: 'AN515-54-58CL',
    picture: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Facer-nitro-5.png?alt=media&token=094ba6a8-1a4d-414a-b32c-c176bfeaca8e',
    rate: 4.5,
    videoReview: 'https://www.youtube.com/embed/8NQFr9De3lU?si=s_lN2KTQresD-36Y',
    tags: ['Baixou'],
    price: 6499.99,
  }, {
    name: 'Notebook Gamer Dell G5',
    description: 'O Dell G5 oferece uma experiência de jogo fluida e gráficos de alta qualidade.',
    brand: 'Dell',
    model: 'G5-5590-A30B',
    picture: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fdell-g5.png?alt=media&token=ac1cb3fa-4cc4-4f30-a831-19bca5b85644',
    rate: 5,
    videoReview: 'https://www.youtube.com/embed/N5C1ALQkv1Q?si=KuVr4V6-A02Z23XK',
    tags: [],
    price: 7299.99,
  }, {
    name: 'Notebook Gamer Lenovo Legion Y540',
    description: 'O Lenovo Legion Y540 é um notebook gamer de alta performance com design elegante.',
    brand: 'Lenovo',
    model: 'Legion Y540-15IRH',
    picture: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Flegion-y540.png?alt=media&token=b36f6c61-8b7d-4454-9940-d945b89d44f8',
    rate: 4.5,
    videoReview: 'https://www.youtube.com/embed/knhriyVTMpA?si=3RduZcEVx4mjEwER',
    tags: ['Recomendado'],
    price: 6999.99,
  }, {
    name: 'Notebook Gamer HP Pavilion',
    description: 'O HP Pavilion é um notebook gamer com desempenho sólido e design moderno, perfeito para jogadores que buscam custo-benefício.',
    brand: 'HP',
    model: 'Pavilion 15-dk0010',
    picture: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fhp-pavilion-dk0010.png?alt=media&token=6f0d7c8d-0612-4ca9-9ee8-1849971ae8c4',
    rate: 4,
    videoReview: 'https://www.youtube.com/embed/dCvvugSjnZ4?si=zOMGbydgNdkB9QwY',
    tags: [],
    price: 5499.99,
  }, {
    name: 'Notebook Gamer ASUS TUF A15',
    description: 'O ASUS TUF Gaming A15 combina durabilidade militar com um desempenho excelente para jogos.',
    brand: 'ASUS',
    model: 'TUF A15 FA506IV',
    picture: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fasus-tuf-a15.png?alt=media&token=989d3375-f26b-4ada-a920-afa41dfdb8de',
    rate: 5,
    videoReview: 'https://www.youtube.com/embed/v-LmH_Gfnn8?si=IGQmsvb-eZyDInwV',
    tags: ['Oportunidade'],
    price: 7499.99,
  }, {
    name: 'Notebook Gamer MSI GL65 Leopard',
    description: 'O MSI GL65 Leopard oferece um desempenho superior com design agressivo e teclado RGB personalizável.',
    brand: 'MSI',
    model: 'GL65 Leopard 10SFK-062',
    picture: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fmsi-gl65.png?alt=media&token=24798828-8546-4720-bfe7-f813f4e78507',
    rate: 4,
    videoReview: 'https://www.youtube.com/embed/uT-YHREKDaE?si=Z7e2lk9G-H7-cghs',
    tags: ['Melhor RTX 2070'],
    price: 8999.99,
  }, {
    name: 'Notebook Gamer Razer Blade 15',
    description: 'O Razer Blade 15 é um notebook gamer premium com design ultrafino e hardware de ponta.',
    brand: 'Razer',
    model: 'Blade 15 Base',
    picture: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Frazer-blade-15.png?alt=media&token=6e23866d-56d0-4da9-94e8-feb1b57d8fac',
    rate: 5,
    videoReview: 'https://www.youtube.com/embed/7kpreUxmHvA?si=wj5A9bw4F8zm_w_Y',
    tags: [],
    price: 12499.99,
  }, {
    name: 'Notebook Gamer Alienware m15',
    description: 'O Alienware m15 é um notebook gamer de alto desempenho com design futurista e recursos avançados.',
    brand: 'Dell',
    model: 'm15 R3',
    picture: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Falienware-m15.png?alt=media&token=85df89d1-3db1-4978-9581-4802b42d7c6e',
    rate: 4.5,
    videoReview: 'https://www.youtube.com/embed/OywbZPwHJBw?si=cZmqJESmXGh-D1Bw',
    tags: ['Sem juros'],
    price: 14999.99,
  }, {
    name: 'Processador AMD Ryzen 7 5700X3D',
    description: 'Desfrute de velocidades supersônicas com 8 núcleos e 16 threads de processamento, prontos para enfrentar os títulos mais desafiadores. Frequência base de 3,0GHz e boost dinâmico de até 4,1GHz para eliminar qualquer engasgo.',
    brand: 'AMD',
    model: '100-100001503WOF',
    picture: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fryzen-7-5700x3d.png?alt=media&token=62caf240-b3c6-41d9-889a-c4ca882822d9',
    rate: 4.5,
    videoReview: 'https://www.youtube.com/embed/ic8a_L15Z98&t=67s',
    tags: ['Sem juros', 'Mais Vendidos', 'Custo Benefício'],
    price: 2499.99,
  }, {
    name: 'Processador Intel Core i9-13900K',
    description: 'O Intel Core i9-13900K é o processador ideal para gamers e profissionais que precisam de desempenho extremo. Equipado com 24 núcleos e 32 threads, alcança frequências de até 5,8 GHz em modo turbo, oferecendo desempenho inigualável.',
    brand: 'Intel',
    model: 'BX8071513900K',
    picture: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fcore-i9-13900k.png?alt=media&token=9d185bf6-64ca-48bf-bdb7-acd0de317f09',
    rate: 4.8,
    videoReview: 'https://www.youtube.com/embed/tV-FbmLJejg',
    tags: ['Desempenho Máximo', 'Recomendado para Jogos', 'Overclock'],
    price: 3899.99,
  }
]

export default goodsList